vocab:
  vocab_prefix: "PhoNER_COVID19"
  unk_piece: "<UNK>"
  bos_piece: "<BOS>"
  eos_piece: "<EOS>"
  pad_piece: "<PAD>"
  path:
    train: "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//train_syllable_preprocessed.json"
    val:   "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//dev_syllable_preprocessed.json"
    test:  "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//test_syllable_preprocessed.json"
  text: "words"
  label: "tags"
  max_length: 64
  task_type: "seq_labeling" # or classification
# --- Global Settings ---
seed: 42
checkpoint_dir: "checkpoints/BiLSTM_PhoNER_COVID19/"

# --- Dataset Definitions ---
datasets:
  phoner_syllable:
    train_path: "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//train_syllable_preprocessed.json"
    val_path: "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//dev_syllable_preprocessed.json"
    test_path: "E://DS201.Q11//DS201//Lab_3//data//PhoNER_COVID19//data//syllable//test_syllable_preprocessed.json"

# --- Model Definitions ---
models:
  BiLSTM: models.BiLSTM.BiLSTM 

# --- Experiment Definition ---
experiments:
  - name: "BiLSTM_PhoNER_COVID19"
    model: "BiLSTM"
    dataset: "phoner_syllable"
    hyperparameters:
      epochs: 50
      early_stop_patience: 10
      lr: 0.002
      weight_decay: 0.00001
      batch_size: 64
      optimizer: "Adam"
      step_size: 30
      gamma: 0.1 
      optimizer_params: {}